export const REQUEST_ADD_CART_PRODUCT = 'REQUEST_ADD_CART_PRODUCT'
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT'
export const REQUEST_REMOVE_CART_PRODUCT = 'REQUEST_REMOVE_CART_PRODUCT'
export const REMOVE_CART_PRODUCTS = 'REMOVE_CART_PRODUCT'
export const GET_ALL_CART_PRODUCTS = 'GET_ALL_CART_PRODUCTS'
export const REQUEST_PAY = 'REQUEST_PAY'
export const PAY = 'PAY'

